test:
	../../trinity-plugins/collectl/examine_resource_usage_profiling.pl ex1
	../../trinity-plugins/collectl/examine_resource_usage_profiling.pl ex2
	touch test

clean:
	rm -f ex1.* ex2.*
	rm -f ./test



