
test:
	../../Analysis/DifferentialExpression/Glimma.Trinity.Rscript --samples_file samples.txt --DE_results my.DE_results --counts_matrix my.counts.matrix
	touch test

clean:
	rm -rf ./glimma
	rm -f ./cpm.DE_results.csv
	rm -f ./test



