
test_trinity:
	./runMe.sh


test:
	./runMe.sh
	./misc_run_tests/__test_runMe_include_normalization.sh
	./misc_run_tests/__runMe_with_qual_trimming.sh
	./misc_run_tests/__runMe_qualTrim_and_norm.sh
	./misc_run_tests/__test_runMe_with_jaccard_clip.sh

test_full:
	./runMe.sh 1

clean:
	./cleanme.pl

