= Gene Ontology Enrichment using Trinotate and GOseq =

The following describes how to use Trinotate and GOseq to explore functional enrichment among gene sets.

[NOTE]
This combined Trinotate/GOseq system hasn't been rigorously tested, benchmarked, or as of yet published, so use for exploratory purposes. Alternatives such as http://www.blast2go.com/b2ghome[Blast2GO] should be considered as potentially more useful and/or accurate alternatives, yet the system here can be quite useful and readily accessible.

== Run Trinotate to Generate an Annotation Report ==

Use http://trinotate.sf.net[Trinotate] to generate an annotation report 'trinotate.xls', which includes top-matching blast matches from SwissProt (and optionally UniRef) and any corresponding Gene Ontology (GO) assignments from the TrEMBL/SwissProt databases.

== Extract GO assignments per gene ==

Extract all GO assignments for each gene feature, including all parent terms within the GO DAG, using a script included in Trinotate (not Trinity) like so:

  ${TRINOTATE_HOME}/util/extract_GO_assignments_from_Trinotate_xls.pl --Trinotate_xls trinotate.xls \
                                                                      -G --include_ancestral_terms \
                                                                    > go_annotations.txt


== Run GOseq ==

The Bioconductor package http://www.bioconductor.org/packages/release/bioc/html/goseq.html[GOseq] can then be used to perform functional enrichment tests, like so:

  ${TRINITY_HOME}/Analysis/DifferentialExpression/run_GOseq.pl --factor_labeling  factor_labeling.txt \
                                                               --GO_assignments go_annotations.txt \
                                                               --lengths gene.lengths.txt

Note, the above script is here in the Trinity software package (not Trinotate).

The 'factor_labeling.txt' file should be of format:

     gene_id (tab) factor

where factor is a string describing that subset of genes.  (Note, future versions will require formatting 'factor (tab) gene_id' instead).

For example:

     my_gene_A (tab) diff_expressed_cond_X_Y
     my_gene_B (tab) diff_expressed_cond_X_Y
     ...
     my_gene_M (tab) diff_cond_W_Z
     my_gene_N (tab) diff_cond_W_Z
     ...

You can come up with whatever gene subset you want and call it whatever you want.  The enrichment tests will be performed separately for 
      each factor defined.

The gene.lengths.txt file has the format

     gene (tab) length

Such a file can be generated by extracting the length info from an RSEM genes.results output file, like so:

     cat RSEM.genes.results | cut -f 1,2 > genes.lengths.txt


== Output format ==

Two outputs will be generated, one containing the enriched categories, and another containing the depleted categories (see .enriched and .depleted files).  Each is formatted like so: 


  category        over_represented_pvalue under_represented_pvalue        numDEInCat      numInCat        over_represented_FDR    go_term
  GO:0006950      2.31865343285843e-06    0.999999300797978       29      865     0.0194486974248318      BP response to stress
  GO:0050896      4.21926400365154e-06    0.999998538716346       37      1260    0.0194486974248318      BP response to stimulus
  GO:0005991      1.46319165581868e-05    0.99999948534722        5       13      0.0335131128161946      BP trehalose metabolic process
  GO:0034599      1.53076318362736e-05    0.999998405098904       8       68      0.0335131128161946      BP cellular response to oxidative stress
  GO:0005984      1.81761106498506e-05    0.99999886707966        6       28      0.0335131128161946      BP disaccharide metabolic process
  GO:0016491      2.85213785315928e-05    0.999992430044754       18      384     0.0438230981137924      MF oxidoreductase activity
  GO:0009311      6.17142027090978e-05    0.999995031367248       6       36      0.0812776049678818      BP oligosaccharide metabolic process
  GO:0006979      7.43934748203219e-05    0.999990139968793       8       86      0.0829156739562135      BP response to oxidative stress
  GO:0033554      8.56780402612919e-05    0.999971893243069       22      725     0.0829156739562135      BP cellular response to stress
  GO:0051716      8.9939986935908e-05     0.999966321461546       29      1062    0.0829156739562135      BP cellular response to stimulus
  GO:0009628      0.000216085667513453    0.999952957354358       11      178     0.176369334253296       BP response to abiotic stimulus
  GO:0004601      0.000248703909891837    0.999994839511817       3       8       0.176369334253296       MF peroxidase activity
  GO:0016684      0.000248703909891837    0.999994839511817       3       8       0.176369334253296       MF oxidoreductase activity, acting on peroxide as acceptor
  GO:0070887      0.00026865285434211     0.999935263149842       12      216     0.176907904584279       BP cellular response to chemical stimulus

